base: &base
  adapter: postgresql
  encoding: utf8
  username:
  password:
  host: localhost
  pool: 5

development:
  <<: *base
  database: snoozypost

test:
  <<: *base
  database: snoozypost

production:
  <<: *base
  database: snoozypost
